apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
bases:
  - ../../base
patches:
  - path: 01-add-label.patch.yaml
    target:
      kind: Service
      labelSelector: "app.kubernetes.io/name=vault"
  - path: 02-add-label.patch.yaml
    target:
      kind: Service
      labelSelector: "app.kubernetes.io/name=vault"
  - path: 03-add-label.patch.yaml
    target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=vault-agent-injector"
  - path: 04-add-label.patch.yaml
    target:
      kind: Service
      labelSelector: "app.kubernetes.io/name=vault-agent-injector"
