apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator.yaml
  # https://github.com/istio/istio/blob/master/samples/addons/extras/prometheus-operator.yaml
  - prometheus-operator.yaml
