apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo-istio
spec:
  replicas: 5
  revisionHistoryLimit: 2
  strategy:
    canary:
      maxUnavailable: 1
      maxSurge: "20%"
  selector:
    matchLabels:
      app.kubernetes.io/name: rollouts-demo-istio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rollouts-demo-istio
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:green
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
