name: Test

on: [pull_request, push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install k8s tools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          setup-tools: |
            kubectl
            kustomize
            kubeval
            conftest
          kubectl: '1.21.3'
          kustomize: '4.4.0'
          kubeval: '0.16.1'
          conftest: '0.28.1'
      - name: Validate kustomization
        # Note: enable --strict on kubeval
        run: |
          find . -path "./services/**/overlays/development" -type d -print0 | while read -d $'\0' dir
          do
            echo "::group:: Testing $dir"
            kustomize build $dir | kubeval --ignore-missing-schemas --skip-kinds Rollout
            kustomize build $dir | conftest test -p .github/policy -
            echo "::endgroup:: Testing $dir"
          done
          true
  dry-run:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "Deploying to on branch $GITHUB_REF"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Diff kustomization
        run: |
          set +e
          diff=$(kubectl diff -k ./services/developer-experience/rollouts-demo/overlays/development)
          exit_code=$?
          set -e
          case $exit_code in
            0) printf '%s\n' "No differeneces"; exit 0;;
            1) printf '%s\n' "Found differeneces\n$diff"; exit 0;;
            *) exit $exit_code
          esac

  auto-merge:
    runs-on: ubuntu-latest
    needs: [dry-run]
    if: ${{ github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref, 'gh-pr-') }}
    steps:
      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GH_REPO: ${{ github.repository }}
          PR: ${{ github.event.pull_request.number }}
        run: |
          echo "Merging PR #${{ github.event.pull_request.number }}"
          gh pr merge $PR --merge --auto

  release:
    runs-on: ubuntu-latest
    needs: [dry-run]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo "Deploying to on branch $GITHUB_REF"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Apply kustomization
        run: kubectl apply -k ./services/developer-experience/rollouts-demo/overlays/development
