name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@7cad6034ae7905a72e9454dd1f91d93dd79c996a
        with:
          kubectl: 1.21.3
          kustomize: 4.4.0
          kubeval: 0.15.0
          conftest: 0.28.1
          command: |
            kustomize build ./services/developer-experience/rollouts-demo/overlays/development | kubeval --strict --skip-kinds Rollout
            kustomize build ./services/developer-experience/rollouts-demo/overlays/development | conftest test -p .github/policy -

  dry-run:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "Deploying to on branch $GITHUB_REF"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Diff kustomization
        run: |
          set +e
          diff=$(kubectl diff -k ./services/developer-experience/rollouts-demo/overlays/development)
          exit_code=$?
          set -e
          case $exit_code in
            0) printf '%s\n' "No differeneces"; exit 0;;
            1) printf '%s\n' "Found differeneces\n$diff"; exit 0;;
            *) exit $exit_code
          esac

  release:
    runs-on: ubuntu-latest
    needs: [dry-run]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo "Deploying to on branch $GITHUB_REF"
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}

      - name: Apply kustomization
        run: kubectl apply -k ./services/developer-experience/rollouts-demo/overlays/development
