name: test

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate kustomization
        uses: stefanprodan/kube-tools@7cad6034ae7905a72e9454dd1f91d93dd79c996a
        with:
          kubectl: 1.21.3
          kustomize: 4.4.0
          kubeval: 0.15.0
          conftest: 0.28.1
          command: |
            kustomize build ./services/developer-experience/rollout-demo/overlays/development | kubeval --strict --skip-kinds Rollout
            kustomize build ./services/developer-experience/rollout-demo/overlays/development | conftest test -p .github/policy -

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - run: echo "Deploying to on branch $GITHUB_REF"
      - name: Checkout
        uses: actions/checkout@v2
      - name: K8S get current-context
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: config current-context

      - name: K8S get nodes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: get nodes

      - name: K8S apply
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
        with:
          args: apply -k ./services/developer-experience/rollout-demo/overlays/development
